#!/usr/bin/env python3
"""Exploratory COMBAT outcome anchoring for Stage 6.

This script uses the paired public COMBAT RNA-CyTOF manifest generated by
stage6_combat_paired_rna_flow_bridge.py. It tests prespecified RNA, flow, and
simple composite multiscale features against 28-day death without building a
clinical prediction model.
"""

from __future__ import annotations

import math
from pathlib import Path

import pandas as pd


ROOT = Path("<PROJECT_ROOT>")
OUT = ROOT / "03_results" / "stage6_multiscale_coevent_bridge"
PAIRED = OUT / "stage6_combat_paired_rna_flow_sample_manifest.csv"


def zscore(series: pd.Series) -> pd.Series:
    vals = pd.to_numeric(series, errors="coerce")
    sd = vals.std()
    if pd.isna(sd) or sd == 0:
        return vals * float("nan")
    return (vals - vals.mean()) / sd


def bh_adjust(pvalues: list[float]) -> list[float]:
    n = len(pvalues)
    order = sorted(range(n), key=lambda i: pvalues[i])
    q = [float("nan")] * n
    prev = 1.0
    for rank, i in enumerate(reversed(order), start=1):
        raw = pvalues[i] * n / (n - rank + 1)
        prev = min(prev, raw)
        q[i] = min(prev, 1.0)
    return q


def spearman_approx(x: pd.Series, y: pd.Series) -> tuple[float, float]:
    xr = x.rank(method="average")
    yr = y.rank(method="average")
    rho = xr.corr(yr)
    n = len(xr)
    if pd.isna(rho) or n < 4:
        return float("nan"), float("nan")
    z = float(rho) * math.sqrt(max(n - 1, 1))
    p = math.erfc(abs(z) / math.sqrt(2))
    return float(rho), float(p)


def main() -> None:
    df = pd.read_csv(PAIRED)
    df["Death28"] = pd.to_numeric(df["Death28"], errors="coerce")
    df["multiscale_decoupling_index"] = (
        zscore(df["rna_decoupling_index_six_minus_mhcii"]) + zscore(df["cd3_cd14_abundance_normalized"])
    )
    df["mhcii_low_coevent_high_index"] = zscore(df["cd3_cd14_abundance_normalized"]) - zscore(df["mhcii_cd74_axis"])

    metrics = [
        "six_gene_panel",
        "mhcii_cd74_axis",
        "hla_dr_core",
        "myeloid_inflammatory",
        "immunometabolic_stress",
        "adaptive_t_cell_context",
        "rna_decoupling_index_six_minus_mhcii",
        "rna_decoupling_index_myeloid_minus_mhcii",
        "cd3_cd14_double_fraction",
        "cd3_cd14_abundance_normalized",
        "cd3_cd14_hmean_enrichment_exclusive",
        "double_event_hla_dr_pos_fraction",
        "double_event_cd33_pos_fraction",
        "double_event_cd11c_pos_fraction",
        "double_event_cd16_pos_fraction",
        "double_event_cd38_pos_fraction",
        "multiscale_decoupling_index",
        "mhcii_low_coevent_high_index",
    ]
    scopes = [
        ("infection_all", df[df["analysis_group"].ne("HV")].copy()),
        ("sepsis_only", df[df["analysis_group"].eq("Sepsis")].copy()),
    ]
    rows = []
    for scope_name, scope_df in scopes:
        for metric in metrics:
            if metric not in scope_df.columns:
                continue
            sub = scope_df[[metric, "Death28", "analysis_group"]].dropna()
            if len(sub) < 12 or sub["Death28"].nunique() < 2:
                continue
            alive = sub[sub["Death28"].eq(0)][metric]
            dead = sub[sub["Death28"].eq(1)][metric]
            if len(alive) < 5 or len(dead) < 3:
                continue
            rho, p = spearman_approx(sub[metric], sub["Death28"])
            rows.append(
                {
                    "analysis_scope": scope_name,
                    "outcome": "Death28",
                    "metric": metric,
                    "n": len(sub),
                    "n_alive": len(alive),
                    "n_dead": len(dead),
                    "median_alive": alive.median(),
                    "median_dead": dead.median(),
                    "delta_dead_minus_alive": dead.median() - alive.median(),
                    "spearman_rho_with_death": rho,
                    "p_value_asymptotic_normal_approx": p,
                    "analysis_groups": ";".join(sorted(sub["analysis_group"].astype(str).unique())),
                }
            )
    out = pd.DataFrame(rows)
    if not out.empty:
        out["bh_fdr"] = bh_adjust(out["p_value_asymptotic_normal_approx"].fillna(1.0).tolist())
        out["claim_use"] = out.apply(
            lambda row: "supporting_if_replicated"
            if row["analysis_scope"] == "sepsis_only" and row["bh_fdr"] <= 0.10
            else "exploratory",
            axis=1,
        )
    out.to_csv(OUT / "stage6_combat_multiscale_outcome_associations.csv", index=False)

    top = out.sort_values(["bh_fdr", "p_value_asymptotic_normal_approx"]).head(16) if not out.empty else out
    top_text = top.to_csv(index=False) if not top.empty else "No outcome associations computed."
    scope_counts = (
        pd.concat(
            [
                pd.DataFrame(
                    {
                        "analysis_scope": [name],
                        "n": [len(s.dropna(subset=["Death28"]))],
                        "n_death28": [int(s["Death28"].eq(1).sum())],
                    }
                )
                for name, s in scopes
            ],
            ignore_index=True,
        )
        if scopes
        else pd.DataFrame()
    )
    status = f"""# Stage 6 COMBAT Multiscale Outcome Bridge STATUS

Generated: 2026-06-12

## STATUS

PASS_WITH_EXPLORATORY_OUTCOME_ANCHOR

## Scope Counts

```csv
{scope_counts.to_csv(index=False)}
```

## Interpretation Boundary

This is an exploratory clinical anchor using public COMBAT 28-day death labels. It is not a prognostic model, not external clinical validation, and not a replacement for restricted MIMIC-IV/eICU validation. The Sepsis-only scope is prioritized for claim safety, but event count remains small.

## Top Associations

```csv
{top_text}
```

## Retained Or Discard Decision

retained_or_discard_decision: `RETAIN_AS_EXPLORATORY_CLINICAL_ANCHOR_ONLY`

## Output Files

- `03_results/stage6_multiscale_coevent_bridge/stage6_combat_multiscale_outcome_associations.csv`
"""
    (OUT / "stage6_combat_multiscale_outcome_STATUS.md").write_text(status)
    print(f"outcome_associations={out.shape[0] if not out.empty else 0}")
    if not top.empty:
        print(top.head(10).to_string(index=False))


if __name__ == "__main__":
    main()
